#!/bin/bash

__ifconfig__=$(ifconfig -a)

echo $__ifconfig__
echo $__ifconfig__ | grep -e "^.*: "
echo $__ifconfig__ | grep -e "\(inet\|ether\) 192\.168\(\.[0-9]*\)\{2\}  netmask \([0-9]*\.\)*[0-9]*"
